---
upstream_project_url: {{cookiecutter.upstream_repo}}
upstream_package_name: {{cookiecutter.upstream_repo_name}}
downstream_package_name: {{cookiecutter.project_slug}}

upstream_tag_template: v{version}

specfile_path: {{cookiecutter.project_slug}}.spec

srpm_build_deps:
  - git
  - make

update_release: false

actions:
  # The last step here is required by Packit to return the archive name
  # https://packit.dev/docs/configuration/actions#create-archive
  create-archive:
    - bash -c "make sources"
    - bash -c "ls -1 *.crate"

jobs:
  # Build RPMs for each pull request
  - job: copr_build
    trigger: pull_request
    owner: "r0x0d"
    project: {{cookiecutter.project_slug}}
    targets:
      - fedora-all

  # Build RPMs for main branch
  - job: copr_build
    trigger: commit
    branch: main
    owner: "r0x0d"
    project: {{cookiecutter.project_slug}}
    targets:
      - fedora-all
